# Generated by Django 5.1.4 on 2024-12-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('roll_number', models.CharField(blank=True, max_length=20, null=True)),
                ('class_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
